// <auto-generated />
using System;
using CineReview.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineReview.Migrations
{
    [DbContext(typeof(CineReviewContext))]
    partial class CineReviewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CineReview.Domain.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("CineReview.Domain.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("CineReview.Domain.Midia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Lancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sinopse")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Titulo");

                    b.ToTable("Midias");

                    b.HasDiscriminator<string>("TipoMidia").HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CineReview.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CineReview.Domain.Filme", b =>
                {
                    b.HasBaseType("CineReview.Domain.Midia");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("CineReview.Domain.Serie", b =>
                {
                    b.HasBaseType("CineReview.Domain.Midia");

                    b.Property<int>("Episodios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temporadas")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Serie");
                });

            modelBuilder.Entity("CineReview.Domain.Avaliacao", b =>
                {
                    b.HasOne("CineReview.Domain.Midia", "Midia")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReview.Domain.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineReview.Domain.Favorito", b =>
                {
                    b.HasOne("CineReview.Domain.Midia", "Midia")
                        .WithMany("Favoritos")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReview.Domain.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineReview.Domain.Midia", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Favoritos");
                });

            modelBuilder.Entity("CineReview.Domain.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Favoritos");
                });
#pragma warning restore 612, 618
        }
    }
}
